# Generated by Django 2.2.24 on 2021-11-07 21:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('league_id', models.IntegerField(null=True)),
                ('season_id', models.IntegerField(null=True)),
                ('session_type', models.CharField(default='Open practice + open qualifier + race', max_length=200)),
                ('duration', models.IntegerField(default=3)),
                ('server', models.CharField(default='US-West', max_length=40)),
                ('racers', models.IntegerField(default=58)),
                ('race_start_time', models.TimeField(null=True)),
                ('race_length', models.IntegerField(default=30)),
                ('qual_length', models.IntegerField(default=20)),
                ('fast_repairs', models.IntegerField(default=2)),
                ('inc_first_penalty', models.IntegerField(default=17)),
                ('inc_next_penalty', models.IntegerField(default=5)),
                ('inc_dq', models.IntegerField(default=34)),
                ('damage', models.BooleanField(default=True)),
                ('car_classes', models.CharField(max_length=400, null=True)),
                ('track', models.CharField(max_length=400, null=True)),
                ('practice_state', models.IntegerField(default=72)),
                ('qual_state', models.IntegerField(default=72)),
                ('race_state', models.IntegerField(default=0)),
                ('time_of_day', models.CharField(default='Morning', max_length=40)),
                ('temp', models.IntegerField(default=72)),
                ('humidity', models.IntegerField(default=21)),
                ('clouds', models.CharField(default='Partly Cloudy', max_length=40)),
                ('dynamic', models.BooleanField(default=True)),
                ('generate', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('races', models.ManyToManyField(blank=True, related_name='races', to='db.Race')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
