# Generated by Django 2.2.24 on 2021-11-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='option',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='choices',
            name='selection',
            field=models.CharField(max_length=200),
        ),
    ]
