# Generated by Django 2.2.24 on 2021-11-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20211111_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='race_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='dates',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='tracks',
            field=models.TextField(null=True),
        ),
    ]
