# Generated by Django 2.2.24 on 2021-11-12 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20211112_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='race_date',
        ),
    ]
