# Generated by Django 2.2.24 on 2021-12-21 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0006_remove_race_race_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, null=True)),
                ('make', models.CharField(max_length=30, null=True)),
                ('model', models.CharField(max_length=30, null=True)),
                ('color', models.CharField(max_length=30, null=True)),
                ('picture', models.ImageField(null=True, upload_to='static/images/avatars/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('year',),
            },
        ),
        migrations.DeleteModel(
            name='Choices',
        ),
        migrations.RemoveField(
            model_name='season',
            name='races',
        ),
        migrations.RemoveField(
            model_name='season',
            name='user',
        ),
        migrations.DeleteModel(
            name='Race',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
