# Generated by Django 2.2.24 on 2021-12-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_auto_20211221_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='picture',
            field=models.ImageField(null=True, upload_to='static/images/avatars/'),
        ),
    ]
