# Generated by Django 2.2.24 on 2021-12-21 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_auto_20211221_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='picture',
        ),
    ]
