# Generated by Django 2.2.24 on 2021-12-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_remove_car_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('-year',)},
        ),
        migrations.AddField(
            model_name='car',
            name='picture',
            field=models.ImageField(null=True, upload_to='static/images/avatars/'),
        ),
    ]
