# Generated by Django 2.2.24 on 2021-12-22 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_auto_20211221_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='picture',
        ),
    ]
