# Generated by Django 2.2.24 on 2021-12-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_remove_car_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='front_wheel_width',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='car',
            name='horsepower',
            field=models.IntegerField(default=333),
        ),
        migrations.AddField(
            model_name='car',
            name='rear_wheel_width',
            field=models.FloatField(default=12),
        ),
        migrations.AddField(
            model_name='car',
            name='weight',
            field=models.IntegerField(default=3333),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(default='Multi', max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(default='Vehicle', max_length=30),
        ),
    ]
