# Generated by Django 2.2.24 on 2021-12-22 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_tire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tires', to='db.Car'),
        ),
    ]
