# Generated by Django 2.2.24 on 2021-12-22 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_auto_20211221_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tire',
            options={'ordering': ('-rear_section_width',)},
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='front_wheel_width',
            field=models.FloatField(null=True, verbose_name='Front wheel width [in]'),
        ),
        migrations.AlterField(
            model_name='car',
            name='horsepower',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='rear_wheel_width',
            field=models.FloatField(null=True, verbose_name='Rear wheel width [in]'),
        ),
        migrations.AlterField(
            model_name='car',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='front_section_width',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='rear_section_width',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='treadwear',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Upgrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('induction', models.BooleanField(null=True, verbose_name='Induction system modifications? (e.g. upgrade carbs to fuel injection')),
                ('engine_head', models.BooleanField(null=True, verbose_name='Non-stock heads? (e.g. port/polish, compression changes')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upgrades', to='db.Car')),
            ],
        ),
    ]
