# Generated by Django 2.2.24 on 2021-12-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_auto_20211221_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrades',
            name='boost',
            field=models.BooleanField(default=False, verbose_name='Increased or adjustable boost, or modifications to the wastegate or turbocharger'),
        ),
        migrations.AddField(
            model_name='upgrades',
            name='camshaft',
            field=models.BooleanField(default=False, verbose_name='Non-stock camshaft'),
        ),
        migrations.AddField(
            model_name='upgrades',
            name='cats',
            field=models.BooleanField(default=False, verbose_name='Deleleted catalytic converter'),
        ),
        migrations.AddField(
            model_name='upgrades',
            name='displacement',
            field=models.IntegerField(default=0, verbose_name='Engine displacement as a percentage of the initial displacement'),
        ),
        migrations.AddField(
            model_name='upgrades',
            name='forced_induction',
            field=models.BooleanField(default=False, verbose_name='Added a turbo or supercharger?'),
        ),
        migrations.AddField(
            model_name='upgrades',
            name='headers',
            field=models.BooleanField(default=False, verbose_name='Non-stock exhaust manifold or headers'),
        ),
        migrations.AddField(
            model_name='upgrades',
            name='muffler',
            field=models.BooleanField(default=False, verbose_name='Upgraded or deleted muffler'),
        ),
        migrations.AlterField(
            model_name='upgrades',
            name='engine_head',
            field=models.BooleanField(default=False, verbose_name='Non-stock heads (e.g. port/polish, compression changes)'),
        ),
        migrations.AlterField(
            model_name='upgrades',
            name='induction',
            field=models.BooleanField(default=False, verbose_name='Induction system modifications (e.g. upgrade carbs to fuel injection)'),
        ),
    ]
