# Generated by Django 2.2.24 on 2021-12-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0019_auto_20211221_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrades',
            name='adj_sway',
            field=models.BooleanField(default=False, verbose_name='Non-stock adjustable sway bar(s)'),
        ),
        migrations.AddField(
            model_name='upgrades',
            name='aftermarket_aero',
            field=models.BooleanField(default=False, verbose_name='Any aftermarket aero devices.'),
        ),
        migrations.AddField(
            model_name='upgrades',
            name='brakes',
            field=models.BooleanField(default=False, verbose_name='Brake Upgrades (other than drilled/gas slotted stock rotors, brake pads, master cylinder, or aftermarket rotors with no increase in diameter). Includes factory or post-delivery installation of ceramic brakes'),
        ),
        migrations.AddField(
            model_name='upgrades',
            name='camber',
            field=models.BooleanField(default=False, verbose_name='Any change to the suspension components or mounting points to increase available negative camber'),
        ),
        migrations.AddField(
            model_name='upgrades',
            name='custom_suspension',
            field=models.BooleanField(default=False, verbose_name='Suspension changes to lower a car that require machining, welding, etc. or their equivalent.'),
        ),
        migrations.AddField(
            model_name='upgrades',
            name='differential',
            field=models.BooleanField(default=False, verbose_name='Non-stock differential'),
        ),
        migrations.AddField(
            model_name='upgrades',
            name='factory_aero',
            field=models.BooleanField(default=False, verbose_name='Non-stock aero devices that came from another car within the same model series.'),
        ),
        migrations.AddField(
            model_name='upgrades',
            name='final_drive',
            field=models.BooleanField(default=False, verbose_name='Non-stock final drive ratio'),
        ),
        migrations.AddField(
            model_name='upgrades',
            name='fixed_sway',
            field=models.BooleanField(default=False, verbose_name='Non-stock non-adjustable sway bar(s)'),
        ),
        migrations.AddField(
            model_name='upgrades',
            name='oem_aero',
            field=models.BooleanField(default=False, verbose_name='Non-stock aero devices that came from another car not within the same model series.'),
        ),
        migrations.AddField(
            model_name='upgrades',
            name='pdk',
            field=models.BooleanField(default=False, verbose_name='Stock or Non-stock PDK or equivalent transmission'),
        ),
        migrations.AddField(
            model_name='upgrades',
            name='shock_tower',
            field=models.BooleanField(default=False, verbose_name='Non-stock shock tower brace'),
        ),
        migrations.AddField(
            model_name='upgrades',
            name='shocks',
            field=models.BooleanField(default=False, verbose_name='Non-stock shocks with external reservoirs or 2+ way adjustability'),
        ),
        migrations.AddField(
            model_name='upgrades',
            name='spherical_bearings',
            field=models.BooleanField(default=False, verbose_name='Installation of “Monoball” suspension bushings or equivalent'),
        ),
        migrations.AddField(
            model_name='upgrades',
            name='tube_frame',
            field=models.BooleanField(default=False, verbose_name='Tube frame chassis'),
        ),
        migrations.AddField(
            model_name='upgrades',
            name='windshield_delete',
            field=models.BooleanField(default=False, verbose_name='Removal or alteration of windshield (other than replacement with lighter weight materials)'),
        ),
    ]
