# Generated by Django 2.2.24 on 2021-12-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0020_auto_20211221_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgrades',
            name='cats',
            field=models.BooleanField(default=False, verbose_name='Deleted catalytic converter'),
        ),
    ]
