# Generated by Django 2.2.24 on 2021-12-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0022_auto_20211225_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgrades',
            name='differential',
            field=models.BooleanField(default=False, verbose_name='Stock or non-stock limited-slip differential'),
        ),
        migrations.AlterField(
            model_name='upgrades',
            name='displacement',
            field=models.IntegerField(default=0, verbose_name='Is the engine displacement larger than stock? If yes, by what percentage? (0=no increase, 100=doubled displacement)'),
        ),
    ]
