# Generated by Django 2.2.24 on 2021-12-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0024_auto_20211227_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='horsepower',
            field=models.IntegerField(null=True, verbose_name='Factory rated HP or measured at the crank. Assume 10% losses to convert wheel HP to crank HP.'),
        ),
        migrations.AlterField(
            model_name='upgrades',
            name='traction_control',
            field=models.BooleanField(default=False, verbose_name='Electronically-controlled shocks and/or active suspension'),
        ),
    ]
