# Generated by Django 2.2.24 on 2021-12-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0025_auto_20211230_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgrades',
            name='traction_control',
            field=models.BooleanField(default=False, verbose_name='Electronically adjustable shocks and/or active suspension'),
        ),
    ]
