# Generated by Django 2.2.24 on 2022-01-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0026_auto_20211230_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgrades',
            name='adj_sway',
            field=models.BooleanField(default=False, verbose_name='Non-stock adjustable sway bar(s) (20 points)'),
        ),
        migrations.AlterField(
            model_name='upgrades',
            name='aftermarket_aero',
            field=models.BooleanField(default=False, verbose_name='Any aftermarket aero devices. (40 points)'),
        ),
        migrations.AlterField(
            model_name='upgrades',
            name='aftermarket_springs',
            field=models.BooleanField(default=False, verbose_name='Aftermarket springs or factory springs from a different model series. (30 points)'),
        ),
        migrations.AlterField(
            model_name='upgrades',
            name='boost',
            field=models.BooleanField(default=False, verbose_name='Increased or adjustable boost, or modifications to the wastegate or turbocharger (100 points)'),
        ),
        migrations.AlterField(
            model_name='upgrades',
            name='brakes',
            field=models.BooleanField(default=False, verbose_name='Brake Upgrades (other than drilled/gas slotted stock rotors, brake pads, master cylinder, or aftermarket rotors with no increase in diameter). Includes factory or post-delivery installation of ceramic brakes (20 points)'),
        ),
        migrations.AlterField(
            model_name='upgrades',
            name='camber',
            field=models.BooleanField(default=False, verbose_name='Any change to the suspension components or mounting points to increase available negative camber (20 points)'),
        ),
        migrations.AlterField(
            model_name='upgrades',
            name='camshaft',
            field=models.BooleanField(default=False, verbose_name='Non-stock camshaft (50 points)'),
        ),
        migrations.AlterField(
            model_name='upgrades',
            name='cats',
            field=models.BooleanField(default=False, verbose_name='Deleted catalytic converter (5 points)'),
        ),
        migrations.AlterField(
            model_name='upgrades',
            name='custom_suspension',
            field=models.BooleanField(default=False, verbose_name='Suspension changes to lower a car that require machining, welding, etc. or their equivalent. (10 points)'),
        ),
        migrations.AlterField(
            model_name='upgrades',
            name='differential',
            field=models.BooleanField(default=False, verbose_name='Is your car AWD and/or have a limited-slip differential? (20 points)'),
        ),
        migrations.AlterField(
            model_name='upgrades',
            name='displacement',
            field=models.IntegerField(default=0, verbose_name='Is the engine displacement larger than stock? If yes, by what percentage? (0=no increase, 100=doubled displacement) (36 x increase% points'),
        ),
        migrations.AlterField(
            model_name='upgrades',
            name='engine_head',
            field=models.BooleanField(default=False, verbose_name='Non-stock heads (e.g. port/polish, compression changes) (50 points)'),
        ),
        migrations.AlterField(
            model_name='upgrades',
            name='factory_aero',
            field=models.BooleanField(default=False, verbose_name='Non-stock aero devices that came from another car within the same model series. (10 points)'),
        ),
        migrations.AlterField(
            model_name='upgrades',
            name='factory_springs',
            field=models.BooleanField(default=False, verbose_name='Non-stock factory springs (within the same series) (15  points)'),
        ),
        migrations.AlterField(
            model_name='upgrades',
            name='final_drive',
            field=models.BooleanField(default=False, verbose_name='Non-stock final drive ratio (40 points)'),
        ),
        migrations.AlterField(
            model_name='upgrades',
            name='fixed_sway',
            field=models.BooleanField(default=False, verbose_name='Non-stock non-adjustable sway bar(s) (10 points)'),
        ),
        migrations.AlterField(
            model_name='upgrades',
            name='forced_induction',
            field=models.BooleanField(default=False, verbose_name='Added a turbo or supercharger? (150 points)'),
        ),
        migrations.AlterField(
            model_name='upgrades',
            name='headers',
            field=models.BooleanField(default=False, verbose_name='Non-stock exhaust manifold or headers (5 points)'),
        ),
        migrations.AlterField(
            model_name='upgrades',
            name='induction',
            field=models.BooleanField(default=False, verbose_name='Induction system modifications (e.g. upgrade carbs to fuel injection) (40 points)'),
        ),
        migrations.AlterField(
            model_name='upgrades',
            name='mid_engine',
            field=models.BooleanField(default=False, verbose_name='Is your car mid-engine or all electric? (15 points)'),
        ),
        migrations.AlterField(
            model_name='upgrades',
            name='muffler',
            field=models.BooleanField(default=False, verbose_name='Upgraded or deleted muffler (5 points)'),
        ),
        migrations.AlterField(
            model_name='upgrades',
            name='oem_aero',
            field=models.BooleanField(default=False, verbose_name='Non-stock aero devices that came from another car not within the same model series. (20 points)'),
        ),
        migrations.AlterField(
            model_name='upgrades',
            name='pdk',
            field=models.BooleanField(default=False, verbose_name='Is your car an EV or does your car have a PDK, dual clutch, or sequential transmission? (15 points)'),
        ),
        migrations.AlterField(
            model_name='upgrades',
            name='shock_tower',
            field=models.BooleanField(default=False, verbose_name='Non-stock shock tower brace (10 point)'),
        ),
        migrations.AlterField(
            model_name='upgrades',
            name='shocks',
            field=models.BooleanField(default=False, verbose_name='Non-stock shocks with external reservoirs or 2+ way adjustability (20 points)'),
        ),
        migrations.AlterField(
            model_name='upgrades',
            name='spherical_bearings',
            field=models.BooleanField(default=False, verbose_name='Installation of “Monoball” suspension bushings or equivalent 10 (points)'),
        ),
        migrations.AlterField(
            model_name='upgrades',
            name='traction_control',
            field=models.BooleanField(default=False, verbose_name='Electronically adjustable shocks and/or active suspension, including PASM (10 points)'),
        ),
        migrations.AlterField(
            model_name='upgrades',
            name='tube_frame',
            field=models.BooleanField(default=False, verbose_name='Tube frame chassis (100 points)'),
        ),
        migrations.AlterField(
            model_name='upgrades',
            name='windshield_delete',
            field=models.BooleanField(default=False, verbose_name='Removal or alteration of windshield (other than replacement with lighter weight materials) (60 points)'),
        ),
    ]
