# Generated by Django 2.2.24 on 2022-01-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0027_auto_20220106_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgrades',
            name='displacement',
            field=models.IntegerField(default=0, verbose_name='Is the engine displacement larger than stock? If yes, by what percentage? (0=no increase, 100=doubled displacement) (36 x fractional increase points'),
        ),
    ]
