# Generated by Django 2.2.24 on 2022-01-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0028_auto_20220111_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgrades',
            name='differential',
            field=models.BooleanField(default=False, verbose_name='Does your car have a stock/aftermarket LSD or AWD? (20 points)'),
        ),
    ]
