# Generated by Django 2.2.24 on 2024-02-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0029_auto_20220111_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='weight',
            field=models.IntegerField(null=True, verbose_name='Curb weight or measured weight [lb]'),
        ),
    ]
