# Generated by Django 2.2.24 on 2025-11-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0030_auto_20240202_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradeDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('points', models.FloatField(default=0)),
                ('per_unit', models.FloatField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'key'],
            },
        ),
    ]
