# Generated by Django 3.2.25 on 2025-12-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '10008_alter_tire_race_tires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='weight',
            field=models.IntegerField(null=True, verbose_name="Curb weight is the weight of the vehicle including a full tank of fuel and all standard equipment. It does not include the weight of the driver, any passengers, or cargo. If modified, I t is preferred to measure the actual weight of your car with a full tank of fuel, and all modifications installed as ready to race. This can be accomplished at shops performing a corner balance alignment, you can Google 'public scales near me' to find DMV weigh stations, or you can email PCA LA requesting scales be brought to the next autocross. Be prepared to show photos proving your car's weight if it is significantly different than its original Curb Weight."),
        ),
    ]
