# Generated by Django 3.2.25 on 2025-12-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '10006_alter_tire_race_tires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='race_tires',
            field=models.BooleanField(default=False, verbose_name='Do you have race tires? Treadwear less than 140, or no official treadwear will automatically put your car into CC18. The only exception to this is for Porsches that are 1998 and older. They will be classed with 200tw “AutoX tire” and then bumped up 2 classes.'),
        ),
    ]
