# Generated by Django 3.2.25 on 2025-12-08 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '10002_auto_20251111_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tire',
            name='dot',
        ),
    ]
