# Generated by Django 3.2.25 on 2025-11-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0031_upgradedefinition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upgrades',
            options={'verbose_name': 'Car Upgrades', 'verbose_name_plural': 'Car Upgrades'},
        ),
        migrations.RemoveField(
            model_name='upgrades',
            name='adj_sway',
        ),
        migrations.RemoveField(
            model_name='upgrades',
            name='aftermarket_aero',
        ),
        migrations.RemoveField(
            model_name='upgrades',
            name='aftermarket_springs',
        ),
        migrations.RemoveField(
            model_name='upgrades',
            name='boost',
        ),
        migrations.RemoveField(
            model_name='upgrades',
            name='brakes',
        ),
        migrations.RemoveField(
            model_name='upgrades',
            name='camber',
        ),
        migrations.RemoveField(
            model_name='upgrades',
            name='camshaft',
        ),
        migrations.RemoveField(
            model_name='upgrades',
            name='cats',
        ),
        migrations.RemoveField(
            model_name='upgrades',
            name='custom_suspension',
        ),
        migrations.RemoveField(
            model_name='upgrades',
            name='differential',
        ),
        migrations.RemoveField(
            model_name='upgrades',
            name='displacement',
        ),
        migrations.RemoveField(
            model_name='upgrades',
            name='engine_head',
        ),
        migrations.RemoveField(
            model_name='upgrades',
            name='factory_aero',
        ),
        migrations.RemoveField(
            model_name='upgrades',
            name='factory_springs',
        ),
        migrations.RemoveField(
            model_name='upgrades',
            name='final_drive',
        ),
        migrations.RemoveField(
            model_name='upgrades',
            name='fixed_sway',
        ),
        migrations.RemoveField(
            model_name='upgrades',
            name='forced_induction',
        ),
        migrations.RemoveField(
            model_name='upgrades',
            name='headers',
        ),
        migrations.RemoveField(
            model_name='upgrades',
            name='induction',
        ),
        migrations.RemoveField(
            model_name='upgrades',
            name='mid_engine',
        ),
        migrations.RemoveField(
            model_name='upgrades',
            name='muffler',
        ),
        migrations.RemoveField(
            model_name='upgrades',
            name='oem_aero',
        ),
        migrations.RemoveField(
            model_name='upgrades',
            name='pdk',
        ),
        migrations.RemoveField(
            model_name='upgrades',
            name='shock_tower',
        ),
        migrations.RemoveField(
            model_name='upgrades',
            name='shocks',
        ),
        migrations.RemoveField(
            model_name='upgrades',
            name='spherical_bearings',
        ),
        migrations.RemoveField(
            model_name='upgrades',
            name='traction_control',
        ),
        migrations.RemoveField(
            model_name='upgrades',
            name='tube_frame',
        ),
        migrations.RemoveField(
            model_name='upgrades',
            name='windshield_delete',
        ),
        migrations.AddField(
            model_name='upgrades',
            name='values',
            field=models.JSONField(default=dict, help_text='Stores upgrade values as {key: value}'),
        ),
    ]
