# Generated by Django 3.2.25 on 2025-12-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '10005_auto_20251208_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='race_tires',
            field=models.BooleanField(default=False, verbose_name='Do you have race tires? Treadwear less than 140, or no official treadwear will automatically put your car into CC18 as the penalty is applied during registration. Be sure to check the box during registration.'),
        ),
    ]
