# Generated by Django 3.2.25 on 2025-11-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '10000_auto_20251111_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='horsepower',
            field=models.IntegerField(null=True, verbose_name="Assume 10% losses to convert wheel HP to crank HP as measured on a wheel dyno [preferred]. If your car dyno'd at 386 whp (wheel horsepower) --> 386*1.10 = 424.6 crank hp --> Enter 425. Note: Be prepared to show your dyno results if a fellow competitor asks."),
        ),
        migrations.AlterField(
            model_name='car',
            name='weight',
            field=models.IntegerField(null=True, verbose_name="Curb weight is the weight of the vehicle including a full tank of fuel and all standard equipment. It does not include the weight of the driver, any passengers, cargo, or optional equipment. If possible, it is preferred to measure the actual weight of your car with a full tank of fuel, no passengers, and all modifications installed as ready to race.  This can be accomplished at shops performing a corner balance alignment, or you can Google 'public scales near me' to find DMV weigh stations.  Be prepared to show photos proving your car's weight if it is significantly different than its original Curb Weight."),
        ),
    ]
