# Generated by Django 3.2.25 on 2025-11-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '10001_auto_20251111_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='front_wheel_width',
            field=models.FloatField(null=True, verbose_name="Front wheel width [in]. To measure wheel width, find the measurement on the wheel's stamp (often XXJ, where XX is the width in inches).  This is the value wheel manufacturers advertise as the wheel width.  Alternatively, you can manually measure the distance between the two bead seats (the inner lips where the tire sits) with a tape measure or straight edge and a ruler. This 'bead seat to bead seat' measurement is the official rim width and will be roughly 1 inch less than the total outer width of the wheel."),
        ),
        migrations.AlterField(
            model_name='tire',
            name='treadwear',
            field=models.IntegerField(null=True, verbose_name="You can find a tire's treadwear rating on its sidewall, stamped as a number under the Uniform Tire Quality Grading (UTQG) system. To find it, look for the words 'TREADWEAR' followed by a number, typically located near the tire's shoulder or maximum width. A higher number indicates a longer expected tread life. If using race tires (anything less than 200 tw), enter 200 tw to class your car, and then a +2 class penalty will be applied during registration."),
        ),
    ]
