# Generated by Django 3.2.25 on 2025-12-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '10004_auto_20251208_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tire',
            name='treadwear',
        ),
        migrations.AlterField(
            model_name='tire',
            name='autox_tires',
            field=models.BooleanField(default=False, verbose_name='Do you have autox tires? Treadwear greater than or equal to 140, but less than or equal to 200 (+20 points)'),
        ),
        migrations.AlterField(
            model_name='tire',
            name='race_tires',
            field=models.BooleanField(default=False, verbose_name='Do you have race tires?Treadwear less than 140, or no official treadwear will automatically put your car into CC18 as the penalty is applied during registration. Be sure to check the box during registration.'),
        ),
        migrations.AlterField(
            model_name='tire',
            name='street_tires',
            field=models.BooleanField(default=False, verbose_name='Do you have street tires? Treadwear greater than 200 (+0 points)'),
        ),
    ]
