# Generated by Django 3.2.25 on 2025-12-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '10003_remove_tire_dot'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='autox_tires',
            field=models.BooleanField(default=False, verbose_name='Treadwear greater than or equal to 140, but less than or equal to 200 (+20 points)'),
        ),
        migrations.AddField(
            model_name='tire',
            name='race_tires',
            field=models.BooleanField(default=False, verbose_name='Treadwear less than 140, or no official treadwear will automatically put your car into CC18 as the penalty is applied during registration. Be sure to check the box during registration.'),
        ),
        migrations.AddField(
            model_name='tire',
            name='street_tires',
            field=models.BooleanField(default=False, verbose_name='Treadwear greater than 200 (+0 points)'),
        ),
    ]
