# Generated by Django 3.2.25 on 2026-01-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '10011_alter_car_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='horsepower',
            field=models.IntegerField(null=True, verbose_name="Enter your car's crank horsepower. This is the horsepower listed by the manufacturer (if your car is not modified). Note that you can not enter a HP lower than the original manufacturer's listed HP. If your car is modified, assume 10% losses to convert wheel HP to crank HP as measured on a wheel dyno (preferred). If your car dyno'd at 386 whp (wheel horsepower) --> 386*1.10 = 424.6 crank hp --> enter 425. Note: Be prepared to show your dyno results if a fellow competitor asks.\n\nCrank Horsepower:"),
        ),
    ]
