# Generated by Django 3.2.25 on 2025-12-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '10009_alter_car_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='car',
            name='front_wheel_width',
            field=models.FloatField(null=True, verbose_name="To measure wheel width, find the measurement on the wheel's stamp (often XXJ, where XX is the width in inches).  This is the value wheel manufacturers advertise as the wheel width.  Alternatively, you can manually measure the distance between the two bead seats (the inner lips where the tire sits) with a tape measure or straight edge and a ruler. This 'bead seat to bead seat' measurement is the official rim width and will be roughly 1 inch less than the total outer width of the wheel.\n\nFront wheel width [in]:"),
        ),
        migrations.AlterField(
            model_name='car',
            name='horsepower',
            field=models.IntegerField(null=True, verbose_name="Enter your car's crank horsepower. This is the horsepower listed by the manufacturer (if your car is not modified). If your car is modified, assume 10% losses to convert wheel HP to crank HP as measured on a wheel dyno (preferred). If your car dyno'd at 386 whp (wheel horsepower) --> 386*1.10 = 424.6 crank hp --> enter 425. Note: Be prepared to show your dyno results if a fellow competitor asks.\n\nCrank Horsepower:"),
        ),
        migrations.AlterField(
            model_name='car',
            name='weight',
            field=models.IntegerField(null=True, verbose_name="Enter your car's curb weight. Curb weight is the weight of the vehicle including a full tank of fuel and all standard equipment. It does not include the weight of the driver, any passengers, or cargo. If modified, it is preferred to measure the actual weight of your car with a full tank of fuel, and all modifications installed as ready to race. This can be accomplished at shops performing a corner balance alignment, you can Google 'public scales near me' to find DMV weigh stations, or you can email PCA LA requesting scales be brought to the next autocross. Be prepared to show photos proving your car's weight if it is significantly different than its original Curb Weight.\n\nCurb Weight:"),
        ),
    ]
