# Generated by Django 2.2.24 on 2021-12-21 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='invitation_key',
        ),
        migrations.DeleteModel(
            name='UserInvitation',
        ),
    ]
