"""
Django settings for jump project.

Generated by 'django-admin startproject' using Django 2.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
from decouple import config
from django.contrib.messages import constants as messages
from helpers.common import server_env

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='your-secret-key-here')

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'America/Los_Angeles'
# TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = False

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# Split long ALLOWED_HOSTS line
ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='localhost,.herokuapp.com,pca-calc.benjaminfulton.com'
).split(',')

# Required for django_comments > django.contrib.sites
SITE_ID = 2

# Application definition

INSTALLED_APPS = [
    'api',
    'users',
    'scripts',
    'hamlpy',
    'widget_tweaks',
    'db.apps.DbConfig',
    'django_comments',
    'django.contrib.sites',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pipeline',
    'administration',
    'explorer',
    'django_select2'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware"
]

ROOT_URLCONF = 'pca_calc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'loaders': (
                # Enable caching by uncommenting the following lines:
                # ('django.template.loaders.cached.Loader', (
                'hamlpy.template.loaders.HamlPyFilesystemLoader',
                'hamlpy.template.loaders.HamlPyAppDirectoriesLoader',
                'django.template.loaders.app_directories.Loader'
                # )),
            ),
            'libraries': {
                'common_helpers': 'helpers.common',
                'star_helpers': 'helpers.star'
            }
        },
    },
]

# Media files (uploads)
MEDIA_URL = '/uploads/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')

# Static files (CSS, JavaScript, Images)
STATIC_SUFFIX = '/static/'
STATIC_URL = STATIC_SUFFIX
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'assets'),
]

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'pipeline.finders.PipelineFinder',
]

if server_env() == "development":
    pipeline_enabled = False

else:
    pipeline_enabled = True

PIPELINE = {
    'PIPELINE_ENABLED': pipeline_enabled,
    'DISABLE_WRAPPER': False,
    'JS_COMPRESSOR': 'pipeline.compressors.uglifyjs.UglifyJSCompressor',
    'CSS_COMPRESSOR': 'pipeline.compressors.yuglify.YuglifyCompressor',
    'COMPILERS': (
        'pipeline.compilers.sass.SASSCompiler',
    ),
    'STYLESHEETS': {
        'application': {
            'source_filenames': (
              'stylesheets/application.scss',
            ),
            'output_filename': 'stylesheets/application.css',
            'extra_context': {
                'media': 'screen,projection',
            },
        },
        'admin': {
            'source_filenames': (
              'stylesheets/admin.scss',
            ),
            'output_filename': 'stylesheets/admin.css',
            'extra_context': {
                'media': 'screen,projection',
            },
        },
    },
    'JAVASCRIPT': {
        'libs': {
            'source_filenames': (
              'javascripts/libs/jquery-3.3.1.js',
              'javascripts/libs/jquery-ui-dragable-1.12.1.js',
              'javascripts/libs/bootstrap.bundle-4.1.3.js',
              'javascripts/libs/js.cookie-3.14.1.min.js',
              'javascripts/libs/moment-2.24.0.js',
              'javascripts/libs/split-1.5.11.js',
              'javascripts/libs/tabulator-4.2.7.js'
            ),
            'output_filename': 'javascripts/libs.js',
        },
        'application': {
            'source_filenames': (
              'javascripts/site_notice.js',
              'javascripts/toggles.js',
              'javascripts/split_layout.js',
              'javascripts/tables/simple_filter.js',
              'javascripts/tables/fancy_filter.js',
              'javascripts/tables/tabulator_utils.js',
              'javascripts/tables/tabulator_columns.js',
              'javascripts/tables/competition_table.js',
              'javascripts/application.js',
            ),
            'output_filename': 'javascripts/application.js',
        },
    }
}

WSGI_APPLICATION = 'pca_calc.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

# Postgres STUFF
if 'DATABASE_URL' in os.environ.keys():
    url = os.environ['DATABASE_URL']
    host = url.split('@')[1].split(':')[0]
    user = url.split("@")[0].split(":")[1][2:]
    password = url.split("@")[0].split(":")[2]
    name = url.split("/")[-1]
else:
    host = config('DB_HOST')
    name = config('DB_NAME')
    user = config('DB_USER')
    password = config('DB_PASSWORD')

DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE', default='django.db.backends.postgresql'),
        'NAME': name,
        'USER': user,
        'PASSWORD': password,
        'HOST': host,
        'PORT': config('DB_PORT', default='5432')
    },
    'readonly': {
        'ENGINE': config('DB_ENGINE', default='django.db.backends.postgresql'),
        'NAME': name,
        'USER': user if 'DATABASE_URL' in os.environ.keys() else 'readonly',
        'PASSWORD': password,
        'HOST': host,
        'PORT': config('DB_PORT', default='5432'),
    }
}

if 'REDIS_URL' in os.environ.keys():
    redis1 = os.environ.get("REDIS_URL") + "/1"
    redis2 = os.environ.get("REDIS_URL") + "/2"
else:
    redis1 = config('REDIS_URL', default="redis://redis:6379/1")
    redis2 = config('REDIS_URL', default="redis://redis:6379/2")

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": redis1,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    "select2": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": redis2,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# Tell select2 which cache configuration to use:
SELECT2_CACHE_BACKEND = "select2"
# SELECT2_CSS = 'stylesheets/libs/_select2.min.css'
# SELECT2_JS = 'javascripts/libs/select2.min.js'

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

# Password validation settings
val_path = 'django.contrib.auth.password_validation'
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': f'{val_path}.UserAttributeSimilarityValidator', 
    },
    {
        'NAME': f'{val_path}.MinimumLengthValidator', 
    },
    {
        'NAME': f'{val_path}.CommonPasswordValidator', 
    },
    {
        'NAME': f'{val_path}.NumericPasswordValidator', 
    },
]

# Django default message tags

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-dark',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = "/user/login"
# INVITATIONS_SIGNUP_REDIRECT = "/user/sign-up"
# INVITATIONS_INVITATION_EXPIRY = 1 # Days
# INVITATIONS_INVITATION_MODEL = 'users.UserInvitation'
# INVITATIONS_INVITATION_ONLY = False

DATA_UPLOAD_MAX_NUMBER_FIELDS = 100000

AUTH_USER_MODEL = 'users.User'

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')

# Password reset settings
PASSWORD_RESET_TIMEOUT = 259200  # 3 days in seconds
PASSWORD_RESET_EMAIL_TEMPLATE = 'registration/password_reset_email.html'
PASSWORD_RESET_CONFIRM_TEMPLATE = 'registration/password_reset_confirm.html'

# Explorer
EXPLORER_CONNECTIONS = {'readonly': 'readonly'}
EXPLORER_DEFAULT_CONNECTION = 'readonly'

# Explorer permissions
def _get_request_user(candidate):
    """Support either a user object or a request carrying one."""
    if hasattr(candidate, "user"):
        return candidate.user
    return candidate

def explorer_view_permission(user_or_request):
    """Check if user has permission to view SQL Explorer."""
    user = _get_request_user(user_or_request)
    return bool(getattr(user, "is_staff", False))

def explorer_change_permission(user_or_request):
    """Check if user has permission to change SQL Explorer."""
    user = _get_request_user(user_or_request)
    return bool(getattr(user, "is_staff", False))

EXPLORER_PERMISSION_VIEW = explorer_view_permission
EXPLORER_PERMISSION_CHANGE = explorer_change_permission

EXPLORER_SCHEMA_EXCLUDE_TABLE_PREFIXES = (
    'auth',
    'db_program_users',
    'django_admin_log',
    'django_comment_flags',
    'django_content_type',
    'django_migrations',
    'django_session',
    'django_site',
    'explorer',
    'users',
)

EXPLORER_TRANSFORMS = [('star', '<a href="/star/{0}" target="_blank">{0}</a>')]
EXPLORER_UNSAFE_RENDERING = True
